train_dataset:
  path: /Users/pierclgr/PycharmProjects/ML4CV/data/div2k/train/
  shuffle: true
  num_workers: 2
  pin_memory: true
  batch_size: 16 # 64
  augment: true
  patch_size: 64
  scales:
    - 2
    - 3
    - 4
  degradation: bicubic
val_dataset:
  path: /Users/pierclgr/PycharmProjects/ML4CV/data/div2k/validation
  shuffle: false
  num_workers: 1
  pin_memory: true
  batch_size: 1
  degradation: bicubic
  scale: 2
  n_images_to_use: 5
image_channels: 3
n_features: 64
seed: 1507
model: MultiPathResidualNetwork
loss: L1Loss
optimizer:
  name: AdamP
  learning_rate: 0.0001 # 0.001
  halving_steps: 40000 # 400000
  betas:
    - 0.9
    - 0.999
  eps: 0.00000001
clip: 10
model_folder: /Users/pierclgr/PycharmProjects/ML4CV/trained_models/
output_model_file: mprnet_final_model
wandb:
  logging: false # true
  run_name: Train_MPRNet
  project_name: ML4CV_project
  entity_name: pierclgr
  n_images_to_log: 3
max_training_steps: 60000 # 600000